# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
languageCode = "en-us"
contentDir = "content/en"
[[en.menu.menu]]
name="Home"
url="#"
weight=1

[bg]
languageCode="bg"
contentDir="content/bg"
[[bg.menu.menu]]
name="Home"
url="#"
weight=10

[cs]
languageCode="cs"
contentDir="content/cs"
[[cs.menu.menu]]
name="Home"
url="#"
weight=10

[da]
languageCode="da"
contentDir="content/da"
[[da.menu.menu]]
name="Home"
url="#"
weight=10

[de]
languageCode="de"
contentDir="content/de"
[[de.menu.menu]]
name="Home"
url="#"
weight=10

[el]
languageCode="el"
contentDir="content/el"
[[el.menu.menu]]
name="Home"
url="#"
weight=10

[es]
languageCode="es"
contentDir="content/es"
[[es.menu.menu]]
name="Home"
url="#"
weight=10

[et]
languageCode="et"
contentDir="content/et"
[[et.menu.menu]]
name="Home"
url="#"
weight=10

[fi]
languageCode="fi"
contentDir="content/fi"
[[fi.menu.menu]]
name="Home"
url="#"
weight=10

[fr]
languageCode="fr"
contentDir="content/fr"
[[fr.menu.menu]]
name="Home"
url="#"
weight=10

[hu]
languageCode="hu"
contentDir="content/hu"
[[hu.menu.menu]]
name="Home"
url="#"
weight=10

[id]
languageCode="id"
contentDir="content/id"
[[id.menu.menu]]
name="Home"
url="#"
weight=10

[it]
languageCode="it"
contentDir="content/it"
[[it.menu.menu]]
name="Home"
url="#"
weight=10

[ja]
languageCode="ja"
contentDir="content/ja"
[[ja.menu.menu]]
name="Home"
url="#"
weight=10

[lt]
languageCode="lt"
contentDir="content/lt"
[[lt.menu.menu]]
name="Home"
url="#"
weight=10

[lv]
languageCode="lv"
contentDir="content/lv"
[[lv.menu.menu]]
name="Home"
url="#"
weight=10

[nl]
languageCode="nl"
contentDir="content/nl"
[[nl.menu.menu]]
name="Home"
url="#"
weight=10

[pl]
languageCode="pl"
contentDir="content/pl"
[[pl.menu.menu]]
name="Home"
url="#"
weight=10

[pt-pt]
languageCode="pt-pt"
contentDir="content/pt-pt"
[[pt-pt.menu.menu]]
name="Home"
url="#"
weight=10

[pt-br]
languageCode="pt-br"
contentDir="content/pt-br"
[[pt-br.menu.menu]]
name="Home"
url="#"
weight=10

[ro]
languageCode="ro"
contentDir="content/ro"
[[ro.menu.menu]]
name="Home"
url="#"
weight=10

[ru]
languageCode="ru"
contentDir="content/ru"
[[ru.menu.menu]]
name="Home"
url="#"
weight=10

[sk]
languageCode="sk"
contentDir="content/sk"
[[sk.menu.menu]]
name="Home"
url="#"
weight=10

[sl]
languageCode="sl"
contentDir="content/sl"
[[sl.menu.menu]]
name="Home"
url="#"
weight=10

[sv]
languageCode="sv"
contentDir="content/sv"
[[sv.menu.menu]]
name="Home"
url="#"
weight=10

[tr]
languageCode="tr"
contentDir="content/tr"
[[tr.menu.menu]]
name="Home"
url="#"
weight=10

[zh]
languageCode="zh"
contentDir="content/zh"
[[zh.menu.menu]]
name="Home"
url="#"
weight=10



# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
